#spring的配置
spring:
  application:
    name: EUREKA-PROVIDER
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis-plus:
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启二级缓存
    cache-enabled: true
    map-underscore-to-camel-case: false

  global-config:
    # 逻辑删除配置
    db-config:
      # 有数据
      logic-not-delete-value: 1
      # 没有数据
      logic-delete-value: 0
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.shop.api.entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: shop-provider-8001 # 修改eureka上的默认描述信息
    prefer-ip-address: true  # 显示服务的IP地址
server:
  port: 8001